
neck_limits:
  up_limit: 190.0
  down_limit: 150.0
  right_limit: 240.0
  left_limit: 120.0
    
neck_velocity_factor:
  velocity: 1.0

neck_initial_position:
  initial_horizontal: 180.0
  initial_vertical: 180.0

    # The following map is suited for Logitech F710
button_index_map:
  button:
    enable_speech: 3 # Button Y
    enable_neck_movement: 0 # Button X
    centralize_neck: 1 # Button A
  axis:
    vertical_movement: 5 # DPad vertical
    horizontal_movement: 4 # DPad horizontal