neck_limits:
  up_limit: 190.0
  down_limit: 150.0
  right_limit: 240.0
  left_limit: 120.0

neck_velocity_factor:
  velocity: 1.0

neck_initial_position:
  initial_horizontal: 180.0
  initial_vertical:
    180.0

    # The following map is suited for Logitech F710
button_index_map:
  button:
    enable_speech: 3 # Button Y
    enable_neck_movement: 0 # Button X
    centralize_neck: 1 # Button A
    enable_emotion: 2 # Button B
  axis:
    vertical_movement: 5 # DPad vertical
    horizontal_movement: 4 # DPad horizontal

emotions:
  up: "happy"
  down: "suspicious"
  right: "angry"
  left: "surprised" 
  reset: "neutral"

bot_message:
  up:
    text: "oi eu sou o boris"
    lang: "pt"
  down:
    # text:
    #   "The FBOT is the Robotics Group at FURG (Federal University of Rio Grande) focused on developing projects in autonomous mobile robotics. ' \
    #   'Their main objective is to prepare students for national and international competitions, applying knowledge in electronics, programming, and artificial intelligence."
    #text: "Tchau meu amigo"
    text: 'Six seven........ four two'
    lang: "en"
  left:
    text: "Eu sou da FURG, a Universidade Federal do Rio Grande, uma instituição pública de ensino superior, reconhecida por sua excelência no ensino, na pesquisa e em extensão"
    lang: "en"
  right:
    text: "Atualmente, sou tetracampeão consecutivo da Competição Brasileira de Robótica, categoria doméstica"
    lang: "en"
